### ISSUE TITLE
Montgomery 

### ISSUE THREAD

**Issue by Safnamusthafa** [bdfd/3.9_Coursera_IBM-Data-Analyst-Professional-Certificate#1]
[Montgomery_Fleet_Equipment_Inventory_FA_PART_1_START (1).csv](https://github.com/BDFD-LearningGround/Coursera_IBM-Data-Analyst-Professional-Certificate_OP/files/13965269/Montgomery_Fleet_Equipment_Inventory_FA_PART_1_START.1.csv)

**Comment by bdfd** [comment]
could you please clear state the problem?
